import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const read = (path) => readFile(new URL(path, root));
const hash = (data) => createHash('sha256').update(data).digest('hex').slice(0, 16);
async function walk(dir) {
  const entries = await readdir(new URL(dir, root), { withFileTypes: true });
  return (await Promise.all(entries.filter((entry) => !entry.name.startsWith('.')).map((entry) => entry.isDirectory() ? walk(`${dir}/${entry.name}`) : `${dir}/${entry.name}`))).flat().sort();
}
// Link-preview images are fetched only by crawlers; keep them out of offline caches.
const assetFiles = (await walk('assets')).filter((file) => !file.startsWith('assets/social/'));
const assetContents = new Map(await Promise.all(assetFiles.map(async (file) => [file, await read(file)])));
const assetURLs = Object.fromEntries(assetFiles.map((file) => [file, `${file}?v=${hash(assetContents.get(file))}`]));
const assetModule = `// Generated by tools/hash-assets.mjs; do not edit by hand.\nexport const ASSET_URLS = Object.freeze(${JSON.stringify(assetURLs, null, 2)});\n`;
const generated = 'src/data/assets.js';
const files = ['app.js', 'app.css', 'manifest.webmanifest', 'favicon.ico', 'LICENSE', ...(await walk('src')).filter((file) => file !== generated), generated, ...assetFiles].sort();
const contents = new Map(await Promise.all(files.map(async (file) => [file, file === generated ? Buffer.from(assetModule) : assetContents.get(file) ?? await read(file)])));
const urls = Object.fromEntries(files.map((file) => [file, `${file}?v=${hash(contents.get(file))}`]));
const modules = files.filter((file) => file.endsWith('.js'));
const imports = Object.fromEntries(modules.map((file) => [`./${file}`, `./${urls[file]}`]));
let html = (await read('index.html')).toString();
html = html.replace(/<!-- ASSET_IMPORTS_START -->[\s\S]*?<!-- ASSET_IMPORTS_END -->/, `<!-- ASSET_IMPORTS_START -->\n  <script type="importmap">${JSON.stringify({ imports })}</script>\n  <!-- ASSET_IMPORTS_END -->`);
html = html.replace(/(src|href)="([^"?]+)(?:\?[^"\s]*)?"/g, (match, attribute, file) => urls[file] ? `${attribute}="${urls[file]}"` : match);
// Runtime fetches, Workers and AudioWorklet imports do not consult the document import map.
// Cache those exact bare URLs too; immutable hash URLs remain fully isolated.
const precache = ['index.html', ...files, ...Object.values(urls)];
const original = (await read('sw.js')).toString();
const policy = original.replace(/const VERSION = '[^']*';/, '').replace(/const PRECACHE = \[[\s\S]*?\];/, '');
const version = `airhive-${hash(JSON.stringify([html, policy, ...files.map((file) => [file, hash(contents.get(file))])]))}`;
const worker = original.replace(/const VERSION = '[^']*';/, `const VERSION = '${version}';`).replace(/const PRECACHE = \[[\s\S]*?\];/, `const PRECACHE = ${JSON.stringify(precache, null, 2)};`);
const check = process.argv.includes('--check');
for (const [file, next] of [[generated, assetModule], ['index.html', html], ['sw.js', worker]]) {
  const previous = await read(file).catch((error) => { if (error.code === 'ENOENT') return Buffer.from(''); throw error; });
  if (previous.toString() === next) continue;
  if (check) throw new Error(`${file}: content hashes are stale; run npm run assets:hash`);
  await writeFile(new URL(file, root), next);
}
console.log(`${check ? 'Verified' : 'Generated'} ${files.length} assets; ${version}`);
